## CAR_PRICE_PRIDICTION

In [1]:
# import libraries
import pandas as pd  # data preprocessing
from sklearn.model_selection import train_test_split  # for data splitting
from sklearn.linear_model import LinearRegression  # regression model 
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder  # encoding techinique
from sklearn.metrics import r2_score  # model evaluation

In [2]:
# data loading 
df=pd.read_csv(r"C:\Users\Admin\Downloads\cardekho.csv")
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,seats
0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,5.0
1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,5.0
2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,5.0
3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,5.0
4,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,5.0

In [3]:
# check null values 
df.isnull().sum()

year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
seats            221
dtype: int64

In [4]:
# fiiling the null values 
df["mileage"]=df["mileage"].fillna(df["mileage"].mean())
df["engine"]=df["engine"].fillna(df["engine"].mean())
df["seats"]=df["seats"].fillna(df["seats"].median())

In [5]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,seats
0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,5.0
1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,5.0
2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,5.0
3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,5.0
4,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,5.0

In [6]:
# handling categorical  column
label=LabelEncoder()     # initializing label model
df["encoded_fuel"]=label.fit_transform(df["fuel"])
var=dict(zip(df["fuel"],df["encoded_fuel"]))
print(var)

df["encoded_seller_type"]=label.fit_transform(df["seller_type"])
var1=dict(zip(df["seller_type"],df["encoded_seller_type"]))
print(var1)

df["encoded_transmission"]=label.fit_transform(df["transmission"])
var2=dict(zip(df["transmission"],df["encoded_transmission"]))
print(var2)

df["encoded_owner"]=label.fit_transform(df["owner"])
var3=dict(zip(df["owner"],df["encoded_owner"]))
print(var3)

{'Diesel': 1, 'Petrol': 3, 'LPG': 2, 'CNG': 0}
{'Individual': 1, 'Dealer': 0, 'Trustmark Dealer': 2}
{'Manual': 1, 'Automatic': 0}
{'First Owner': 0, 'Second Owner': 2, 'Third Owner': 4, 'Fourth & Above Owner': 1, 'Test Drive Car': 3}

In [7]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,seats,encoded_fuel,encoded_seller_type,encoded_transmission,encoded_owner
0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,5.0,1,1,1,0
1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,5.0,1,1,1,2
2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,5.0,3,1,1,4
3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,5.0,1,1,1,0
4,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,5.0,3,1,1,0

In [10]:
# drop original column
df.drop(columns=["fuel","seller_type","transmission","owner"],inplace=True)

In [11]:
df.head()

,year,selling_price,km_driven,mileage,engine,seats,encoded_fuel,encoded_seller_type,encoded_transmission,encoded_owner
0,2014,450000,145500,23.40,1248.0,5.0,1,1,1,0
1,2014,370000,120000,21.14,1498.0,5.0,1,1,1,2
2,2006,158000,140000,17.70,1497.0,5.0,3,1,1,4
3,2010,225000,127000,23.00,1396.0,5.0,1,1,1,0
4,2007,130000,120000,16.10,1298.0,5.0,3,1,1,0

In [12]:
# check duplicate value
df.duplicated().sum()

np.int64(1222)

In [13]:
# drop duplicates values 
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
# feature selection for model 
x=df.drop(columns=["selling_price"])
y=df["selling_price"]

In [20]:
x

,year,km_driven,mileage,engine,seats,encoded_fuel,encoded_seller_type,encoded_transmission,encoded_owner
0,2014,145500,23.40,1248.0,5.0,1,1,1,0
1,2014,120000,21.14,1498.0,5.0,1,1,1,2
2,2006,140000,17.70,1497.0,5.0,3,1,1,4
3,2010,127000,23.00,1396.0,5.0,1,1,1,0
4,2007,120000,16.10,1298.0,5.0,3,1,1,0
...,...,...,...,...,...,...,...,...,...
8121,2013,50000,18.90,998.0,5.0,3,1,1,2
8122,2014,80000,22.54,1396.0,5.0,1,1,1,2
8123,2013,110000,18.50,1197.0,5.0,3,1,1,0
8124,2007,119000,16.80,1493.0,5.0,1,1,1,1
8125,2009,120000,19.30,1248.0,5.0,1,1,1,0

In [16]:
# data splitting
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
# model selection
model=LinearRegression()    # model initialize

# model train
model.fit(x_train,y_train)

LinearRegression()

In [18]:
# model accuracy on test data 
y_pred=model.predict(x_test)
r2_score(y_test,y_pred)

0.5210595773355722

In [19]:
# model accuracy on train data 
y_pred2=model.predict(x_train)
r2_score(y_train,y_pred2)

0.5203950125092038

## PREDICTIVE MODEL

In [23]:
# year	km_driven	mileage	engine	seats	encoded_fuel	encoded_seller_type 	encoded_transmission	encoded_owner
year=int(input("Enter the age of the car:"))
km=int(input("Enter the km_driven:"))
mileage=int(input("Enter mileage of the car:"))
engine=int(input("Enter engine power:"))
seats=int(input("Enter number of seats:"))
fuel=int(input ("Enter the fuel type --> {'Diesel': 1, 'Petrol': 3, 'LPG': 2, 'CNG': 0}:"))
seller_type=int(input("Enter the seller type --> {'Individual': 1, 'Dealer': 0, 'Trustmark Dealer': 2}:"))
transmission=int(input("Enter transmission --> {'Manual': 1, 'Automatic': 0}:"))
owner=int(input("Enter owner type --> {'First Owner': 0, 'Second Owner': 2, 'Third Owner': 4, 'Fourth & Above Owner': 1, 'Test Drive Car': 3}:"))

pred=model.predict([[year,km,mileage,engine,seats,fuel,seller_type,transmission,owner]])
print("Selling price of the car is:",pred.round(2))

Enter the age of the car: 2012
Enter the km_driven: 12000
Enter mileage of the car: 23
Enter engine power: 600
Enter number of seats: 6
Enter the fuel type --> {'Diesel': 1, 'Petrol': 3, 'LPG': 2, 'CNG': 0}: 1
Enter the seller type --> {'Individual': 1, 'Dealer': 0, 'Trustmark Dealer': 2}: 0
Enter transmission --> {'Manual': 1, 'Automatic': 0}: 1
Enter owner type --> {'First Owner': 0, 'Second Owner': 2, 'Third Owner': 4, 'Fourth & Above Owner': 1, 'Test Drive Car': 3}: 0

Selling price of the car is: [176193.42]

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [24]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6906 entries, 0 to 8125
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   year                  6906 non-null   int64
 1   km_driven             6906 non-null   int64
 2   mileage               6906 non-null   float64
 3   engine                6906 non-null   float64
 4   seats                 6906 non-null   float64
 5   encoded_fuel          6906 non-null   int64
 6   encoded_seller_type   6906 non-null   int64
 7   encoded_transmission  6906 non-null   int64
 8   encoded_owner         6906 non-null   int64
dtypes: float64(3), int64(6)
memory usage: 539.5 KB