## LAPTOP_PRICE_PREDECTION

In [1]:
# import libraries
import pandas as pd  # data preprocessing
from sklearn.model_selection import train_test_split  # for data splitting
from sklearn.linear_model import LinearRegression  # regression model 
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder  # encoding techinique
from sklearn.metrics import r2_score  # model evaluation

In [2]:
# data loading 
df=pd.read_csv(r"C:\Users\Admin\Downloads\laptop_data_cleaned.csv")

In [3]:
df.head()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac

In [4]:
# check null values 
df.isnull().sum()

Company        0
TypeName       0
Ram            0
Weight         0
Price          0
TouchScreen    0
Ips            0
Ppi            0
Cpu_brand      0
HDD            0
SSD            0
Gpu_brand      0
Os             0
dtype: int64

In [5]:
# check duplicates value 
df.duplicated().sum()

np.int64(1)

In [6]:
# to permanentely remove duplicate value
df.drop_duplicates(inplace=True)

In [7]:
# To check duplicates value are remove or not 
df.duplicated().sum()

np.int64(0)

In [8]:
# fiiling the null values 
df["Ram"]=df["Ram"].fillna(df["Ram"].mean())
df["HDD"]=df["HDD"].fillna(df["HDD"].mean())
df["SSD"]=df["SSD"].fillna(df["SSD"].median())

In [9]:
df.head()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac

In [10]:
# handling categorical  column
label=LabelEncoder()     # initializing label model
df["encoded_Company"]=label.fit_transform(df["Company"])
var=dict(zip(df["Company"],df["encoded_Company"]))
print(var)

df["encoded_TypeName"]=label.fit_transform(df["TypeName"])
var1=dict(zip(df["TypeName"],df["encoded_TypeName"]))
print(var1)

df["encoded_Cpu_brand"]=label.fit_transform(df["Cpu_brand"])
var2=dict(zip(df["Cpu_brand"],df["encoded_Cpu_brand"]))
print(var2)

df["encoded_Gpu_brand"]=label.fit_transform(df["Gpu_brand"])
var3=dict(zip(df["Gpu_brand"],df["encoded_Gpu_brand"]))
print(var3)

df["encoded_Os"]=label.fit_transform(df["Os"])
var4=dict(zip(df["Os"],df["encoded_Os"]))
print(var4)

{'Apple': 1, 'HP': 7, 'Acer': 0, 'Asus': 2, 'Dell': 4, 'Lenovo': 10, 'Chuwi': 3, 'MSI': 11, 'Microsoft': 13, 'Toshiba': 16, 'Huawei': 8, 'Xiaomi': 18, 'Vero': 17, 'Razer': 14, 'Mediacom': 12, 'Samsung': 15, 'Google': 6, 'Fujitsu': 5, 'LG': 9}
{'Ultrabook': 4, 'Notebook': 3, 'Netbook': 2, 'Gaming': 1, '2 in 1 Convertible': 0, 'Workstation': 5}
{'Intel Core i5': 2, 'Intel Core i7': 3, 'AMD Processor': 0, 'Intel Core i3': 1, 'Other Intel Processor': 4}
{'Intel': 1, 'AMD': 0, 'Nvidia': 2}
{'Mac': 0, 'Others': 1, 'Windows': 2}

In [11]:
df.head()

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os,encoded_Company,encoded_TypeName,encoded_Cpu_brand,encoded_Gpu_brand,encoded_Os
0,Apple,Ultrabook,8,1.37,11.175755,0,1,226.983005,Intel Core i5,0,128,Intel,Mac,1,4,2,1,0
1,Apple,Ultrabook,8,1.34,10.776777,0,0,127.677940,Intel Core i5,0,0,Intel,Mac,1,4,2,1,0
2,HP,Notebook,8,1.86,10.329931,0,0,141.211998,Intel Core i5,0,256,Intel,Others,7,3,2,1,1
3,Apple,Ultrabook,16,1.83,11.814476,0,1,220.534624,Intel Core i7,0,512,AMD,Mac,1,4,3,0,0
4,Apple,Ultrabook,8,1.37,11.473101,0,1,226.983005,Intel Core i5,0,256,Intel,Mac,1,4,2,1,0

In [12]:
# drop original column
df.drop(columns=["Company","TypeName","Cpu_brand","Gpu_brand","Os"],inplace=True)

In [13]:
df.head()

,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD,encoded_Company,encoded_TypeName,encoded_Cpu_brand,encoded_Gpu_brand,encoded_Os
0,8,1.37,11.175755,0,1,226.983005,0,128,1,4,2,1,0
1,8,1.34,10.776777,0,0,127.677940,0,0,1,4,2,1,0
2,8,1.86,10.329931,0,0,141.211998,0,256,7,3,2,1,1
3,16,1.83,11.814476,0,1,220.534624,0,512,1,4,3,0,0
4,8,1.37,11.473101,0,1,226.983005,0,256,1,4,2,1,0

In [14]:
# feature selection for model 
x=df.drop(columns=["Price"])
y=df["Price"]
x

,Ram,Weight,TouchScreen,Ips,Ppi,HDD,SSD,encoded_Company,encoded_TypeName,encoded_Cpu_brand,encoded_Gpu_brand,encoded_Os
0,8,1.37,0,1,226.983005,0,128,1,4,2,1,0
1,8,1.34,0,0,127.677940,0,0,1,4,2,1,0
2,8,1.86,0,0,141.211998,0,256,7,3,2,1,1
3,16,1.83,0,1,220.534624,0,512,1,4,3,0,0
4,8,1.37,0,1,226.983005,0,256,1,4,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1268,4,2.20,0,0,100.454670,500,0,2,3,3,2,2
1269,4,1.80,1,1,157.350512,0,128,10,0,3,1,2
1270,16,1.30,1,1,276.053530,0,512,10,0,3,1,2
1271,2,1.50,0,0,111.935204,0,0,10,3,4,1,2
1272,6,2.19,0,0,100.454670,1000,0,7,3,3,0,2

In [15]:
# data splitting
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
# model selection
model=LinearRegression()    # model initialize

# model train
model.fit(x_train,y_train)

LinearRegression()

In [17]:
# model accuracy on test data 
y_pred=model.predict(x_test)
r2_score(y_test,y_pred)

0.5536662099285754

In [18]:
# model accuracy on train data 
y_pred2=model.predict(x_train)
r2_score(y_train,y_pred2)

0.6588454108149174

## PREDECTIVE MODEL

In [22]:
# Ram	Weight	TouchScreen	Ips	Ppi	HDD	SSD	encoded_Company	encoded_TypeName	encoded_Cpu_brand	encoded_Gpu_brand encoded_Os
Ram=int(input("Enter the ram of laptop:"))
Weight=int(input("Enter the weight of laptop:"))
TouchScreen=int(input("Enter TouchScreen type --> {'No':0, 'yes':1} :"))
Ips=int(input("Enter Ips type --> {'No':0, 'yes':1} :"))
Ppi=int(input("Enter Ppi of the laptop ---> :"))
HDD=int(input("Enter HDD of the laptop ---> :"))
SSD=int(input ("Enter SSD type of laptop -->:"))
Company=int(input("Enter the Company of laptop -->{{'Apple': 1, 'HP': 7, 'Acer': 0, 'Asus': 2, 'Dell': 4, 'Lenovo': 10, 'Chuwi': 3, 'MSI': 11, 'Microsoft': 13, 'Toshiba': 16, 'Huawei': 8, 'Xiaomi': 18, 'Vero': 17, 'Razer': 14, 'Mediacom': 12, 'Samsung': 15, 'Google': 6, 'Fujitsu': 5, 'LG': 9}}:"))
TypeName=int(input("Enterthe Typename --> {'Ultrabook': 4, 'Notebook': 3, 'Netbook': 2, 'Gaming': 1, '2 in 1 Convertible': 0, 'Workstation': 5}:"))
Cpu_brand=int(input("Enter the Cpu type of laptop ---> {'Intel Core i5': 2, 'Intel Core i7': 3, 'AMD Processor': 0, 'Intel Core i3': 1, 'Other Intel Processor': 4}:"))
Gpu_brand=int(input("Enter the Gpu type of laptop -->{'Intel': 1, 'AMD': 0, 'Nvidia': 2}:"))
Os=int(input("Enter the Os value of laptop ---> {'Mac': 0, 'Others': 1, 'Windows': 2}: "))
pred=model.predict([[Company,TypeName,Ram,Weight,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os]])
print("Selling Price of laptop is:",pred)

Enter the ram of laptop: 12
Enter the weight of laptop: 1
Enter TouchScreen type --> {'No':0, 'yes':1} : 0
Enter Ips type --> {'No':0, 'yes':1} : 2
Enter Ppi of the laptop ---> : 3
Enter HDD of the laptop ---> : 1
Enter SSD type of laptop -->: 2
Enter the Company of laptop -->{{'Apple': 1, 'HP': 7, 'Acer': 0, 'Asus': 2, 'Dell': 4, 'Lenovo': 10, 'Chuwi': 3, 'MSI': 11, 'Microsoft': 13, 'Toshiba': 16, 'Huawei': 8, 'Xiaomi': 18, 'Vero': 17, 'Razer': 14, 'Mediacom': 12, 'Samsung': 15, 'Google': 6, 'Fujitsu': 5, 'LG': 9}}: 1
Enterthe Typename --> {'Ultrabook': 4, 'Notebook': 3, 'Netbook': 2, 'Gaming': 1, '2 in 1 Convertible': 0, 'Workstation': 5}: 1
Enter the Cpu type of laptop ---> {'Intel Core i5': 2, 'Intel Core i7': 3, 'AMD Processor': 0, 'Intel Core i3': 1, 'Other Intel Processor': 4}: 0
Enter the Gpu type of laptop -->{'Intel': 1, 'AMD': 0, 'Nvidia': 2}: 1
Enter the Os value of laptop ---> {'Mac': 0, 'Others': 1, 'Windows': 2}:  1

Selling Price of laptop is: [9.86922201]

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(